title: PL&C Reference
remote_theme: pmarsceill/just-the-docs
color_scheme: foo
compress_html:
  blanklines: true
aux_links:
  "Unit Webpage":
    - "https://www.ole.bris.ac.uk/auth-saml/saml/login?apId=_183_1&redirectUrl=https%3A%2F%2Fwww.ole.bris.ac.uk%2Fwebapps%2Fblackboard%2Fexecute%2FcourseMain%3Fcourse_id%3D_247719_1"